from .save_audio_mp3 import (
    SaveAudioMP3Enhanced,
    NODE_CLASS_MAPPINGS as AUDIO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as AUDIO_DISPLAY_NAME_MAPPINGS,
)
from .save_images import (
    SaveImages,
    NODE_CLASS_MAPPINGS as IMAGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_DISPLAY_NAME_MAPPINGS,
)
from .save_video import (
    SaveVideo,
    NODE_CLASS_MAPPINGS as VIDEO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **AUDIO_NODE_CLASS_MAPPINGS,
    **IMAGE_NODE_CLASS_MAPPINGS,
    **VIDEO_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **AUDIO_DISPLAY_NAME_MAPPINGS,
    **IMAGE_DISPLAY_NAME_MAPPINGS,
    **VIDEO_DISPLAY_NAME_MAPPINGS,
}

__all__ = [
    "SaveAudioMP3Enhanced",
    "SaveImages",
    "SaveVideo",
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
]

